### ISSUE TITLE
incorrect link in wadm docs - non-destructive undeploys

### ISSUE THREAD

**Issue by ceejimus** [wasmCloud/wasmcloud.com#149]
In the [docs](https://wasmcloud.com/docs/fundamentals/wadm/api#undeploy) there's a link in a :fire: Danger popout to the top-level wasm repo [issues](https://github.com/wasmCloud/wadm/issues) page. Should it link to this: https://github.com/wasmCloud/wadm/issues/113 ?

I've got another branch for random docs updates on my fork so I could easily update this.

**Comment by connorsmith256** [comment]
@ceejimus I'm just now seeing this, but that works for me! @thomastaylor312 are you okay with this change?
