### ISSUE TITLE
Add documentation on `WASMCLOUD_LABEL_key=value` labels

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud.com#153]

**Comment by connorsmith256** [comment]
Not stale, but updating title since we don't use `HOST_` as the prefix anymore

**Comment by connorsmith256** [comment]
Documented in two places now, yay:
- https://wasmcloud.com/docs/deployment/hosts/labels
- https://wasmcloud.com/docs/reference/host-config
