### ISSUE TITLE
Update wadm docs with new statuses

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmcloud.com#224]
https://github.com/wasmCloud/wadm/pull/223 changed two of the status names. The documentation should be updated to reflect this.

**Comment by omnide** [comment]
This appears to have already been addressed in [a commit from Dec 13th](https://github.com/wasmCloud/wasmcloud.com/commit/23fab42da6215626d0f12511b18de2accd360a2d) and can probably be closed.
