### ISSUE TITLE
Extend documentation on NATS connections to provide comprehensive recommendations

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud.com#247]
We have one documentation page on our RPC/CTL connections https://wasmcloud.com/docs/deployment/security/nats, but it does not include examples on how to create a lattice with stronger security boundaries. As per https://github.com/wasmCloud/wasmCloud/issues/1119, we depend on our NATS connection security to protect the lattice from bad actors.

We should offer recommendations and pointers to NATS documentation on how to set up a secure NATS server environment.

**Comment by connorsmith256** [comment]
@brooksmtownsend do you think https://wasmcloud.com/docs/category/provisioning-nats and/or https://wasmcloud.com/docs/category/lattice-security covers what you wanted to see here?

**Comment by brooksmtownsend** [comment]
I do! Specifically https://wasmcloud.com/docs/deployment/security/nats-segmentation
