### ISSUE TITLE
Installation does not mention Nix install

### ISSUE THREAD

**Issue by aschrijver** [wasmCloud/wasmcloud.com#290]
But the `wash` README does: [Nix install](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-cli/README.md#nix)

**Comment by ricochet** [comment]
Since we moved `wash` into the wasmCloud monorepo, we need to double-check the install command in both the readme and additionally add this to the install page.

**Comment by aschrijver** [comment]
Is this overzealous stale bot?
