### ISSUE TITLE
[DOCS] Add documentation on how to use WebAssembly compositions

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud.com#409]
WebAssembly compositions (aka [wac](https://github.com/bytecodealliance/wac)) is a declarative superset of WIT for describing how components compose together. We should have documentation on how to use this tool in addition to runtime linking over the lattice.

#405 partially addresses this

**Comment by ericgregory** [comment]
With #428 adding the tutorial on the [build-time compositions page](https://wasmcloud.com/docs/concepts/linking-components/linking-at-build) I believe we're all set for this one!
