### ISSUE TITLE
[DOCS] Debugging and where-to-look

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud.com#412]
When it comes to debugging, it's important for developers to know where to look for issues. Under a debugging document we should have pointers to:

- [x] Where log files exist
- [x] How to debug (logging, printing to stderr)
- [x] How to increase the verbosity of logging
- [x] Common issues / FAQ (some of this exists already)
- [ ] How to use the NATS CLI to debug (subbing on topics for events, rpc, etc)

**Comment by ericgregory** [comment]
Some of this is addressed [here](https://github.com/wasmCloud/wasmcloud.com/pull/430) or was already on the host troubleshooting page, but we'll want more detail on NATS debugging (and perhaps to review how we want to structure these docs).

**Comment by brooksmtownsend** [comment]
@ericgregory marked off some of the bullet points to indicate what I think I see! Let me know if there's more to add :)
