### ISSUE TITLE
Add documentation on link names

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud.com#470]
<img width="869" alt="image" src="https://github.com/wasmCloud/wasmcloud.com/assets/12040685/bcbcd01e-c046-4040-8ef2-db576ac40076">

From the 06-20 community call, we spoke extensively about the use of link names in wasmCloud to use logically named different links, potentially between the same two components. The search docs don't pull up a heading for this, so there must not be a piece under the linking at runtime docs that mention link names.

**Comment by ericgregory** [comment]
Resolved by #479
