### ISSUE TITLE
Actor to Actor Example

### ISSUE THREAD

**Issue by suneetnangia** [wasmCloud/wasmcloud.com#59]
No e2e example of actor to actor communication.
The docs explain some of this but I'd like to see an example with all parts are included, when I current try to make actor talk to another actor via actorReceive: true flag in interface, I get the following error:

Host send error Guest call failed for method Rpc.Convert: method not handled Rpc.Convert - unknown method

**Comment by brooksmtownsend** [comment]
Thanks for this issue @suneetnangia ! Moved this issue to our docs repository so we can organize the work here

**Comment by brooksmtownsend** [comment]
Bumping since https://github.com/wasmCloud/examples/pull/199 will address this one 😄
