### ISSUE TITLE
Use `brew install wasm-tools` in the MacOS instructions during the quickstart

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud.com#710]
For mac, there is now a homebrew formula for `wasm-tools`. Instead of running `cargo install wasm-tools` on mac, the docs should recommend a `brew install wasm-tools`.

This is at least present on https://wasmcloud.com/docs/tour/hello-world#choose-your-language

**Comment by ericgregory** [comment]
Resolved by #713
