### ISSUE TITLE
[DOCS] tinygo snippet missing logging import

### ISSUE THREAD

**Issue by colinjlacy** [wasmCloud/wasmcloud.com#719]
In the [Add Persistent Storage](https://wasmcloud.com/docs/tour/add-features?lang=tinygo#add-persistent-storage) section of the quickstart guide, the tinygo snippet is missing an import for `wasi:logging`. It's referenced in the text below, so I copied it from one of the other languages, added it to my `world.wit`, and the app worked.

I didn't try it without the import statement, so I'm not sure if it would work as it's currently written. If so, please feel free to close this issue.

If it does need to be addressed, I'm happy to contribute.

**Comment by ericgregory** [comment]
Thanks @colinjlacy! The Go template uses the `wasilog` module rather than importing `wasi:logging` directly (allowing for some nice idiomatic logging in Go), and this was a good nudge to make that clearer in the quickstart and address a related error.
